#!/usr/bin/env bash
# ax-first installer
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/daangn/ax-first/main/install.sh | bash
#   curl -fsSL https://raw.githubusercontent.com/daangn/ax-first/main/install.sh | bash -s -- --mode submodule
set -euo pipefail

REPO_URL="${AX_FIRST_REPO:-git@github.com:bluecheat/ax.git}"
INSTALL_DIR="${AX_FIRST_HOME:-$HOME/.ax-first}"
BIN_DIR="${AX_FIRST_BIN:-$HOME/.local/bin}"
MODE="standalone"   # standalone | submodule
BRANCH="${AX_FIRST_BRANCH:-main}"

# ───────────────────────────────────────────────────────────
# arg parse
# ───────────────────────────────────────────────────────────
while [ $# -gt 0 ]; do
    case "$1" in
        --mode) MODE="$2"; shift 2 ;;
        --branch) BRANCH="$2"; shift 2 ;;
        --repo) REPO_URL="$2"; shift 2 ;;
        --help|-h)
            cat <<'EOF'
ax-first installer

  --mode standalone     ~/.ax-first/ 에 클론 + ~/.local/bin/ax-first symlink (default)
  --mode submodule      현재 프로젝트에 git submodule add .ax-first-tool
  --branch <name>       특정 브랜치 사용 (default: main)
  --repo <url>          다른 repo URL (default: git@github.com:bluecheat/ax.git)
EOF
            exit 0 ;;
        *) echo "Unknown option: $1" >&2; exit 1 ;;
    esac
done

# ───────────────────────────────────────────────────────────
# pre-flight
# ───────────────────────────────────────────────────────────
say() { printf "\033[36m[ax-first]\033[0m %s\n" "$*"; }
warn() { printf "\033[33m[ax-first]\033[0m %s\n" "$*" >&2; }
die() { printf "\033[31m[ax-first]\033[0m %s\n" "$*" >&2; exit 1; }

command -v git >/dev/null 2>&1 || die "git이 필요해. brew install git"
command -v bash >/dev/null 2>&1 || die "bash 4+ 필요"

# ───────────────────────────────────────────────────────────
# install
# ───────────────────────────────────────────────────────────
case "$MODE" in
  standalone)
    if [ -d "$INSTALL_DIR/.git" ]; then
      say "이미 설치됨 — 업데이트 시도"
      git -C "$INSTALL_DIR" fetch --quiet origin "$BRANCH"
      git -C "$INSTALL_DIR" reset --hard "origin/$BRANCH"
    else
      say "$REPO_URL → $INSTALL_DIR"
      git clone --quiet --branch "$BRANCH" "$REPO_URL" "$INSTALL_DIR"
    fi

    mkdir -p "$BIN_DIR"
    ln -sf "$INSTALL_DIR/bin/ax-first" "$BIN_DIR/ax-first"

    say "설치 완료."
    say "  binary: $BIN_DIR/ax-first"
    say "  source: $INSTALL_DIR"

    if ! echo ":$PATH:" | grep -q ":$BIN_DIR:"; then
      warn "PATH에 $BIN_DIR 추가가 필요해. 다음 한 줄을 ~/.zshrc 또는 ~/.bashrc에 넣어:"
      printf '    export PATH="%s:$PATH"\n' "$BIN_DIR"
    fi
    ;;

  submodule)
    [ -d ".git" ] || die "현재 디렉토리가 git repo가 아님 — submodule 모드는 프로젝트 루트에서 실행"
    if [ -d ".ax-first-tool" ]; then
      say "이미 submodule 존재 — 업데이트"
      git submodule update --remote --merge .ax-first-tool
    else
      say "submodule add $REPO_URL → .ax-first-tool"
      git submodule add -b "$BRANCH" "$REPO_URL" .ax-first-tool
      git submodule update --init --recursive
    fi

    mkdir -p .ax-first
    cat > .ax-first/.bin <<'EOF'
#!/usr/bin/env bash
# Auto-generated by ax-first installer (submodule mode)
exec "$(git rev-parse --show-toplevel)/.ax-first-tool/bin/ax-first" "$@"
EOF
    chmod +x .ax-first/.bin

    say "submodule 설치 완료."
    say "  사용: ./.ax-first/.bin <command>  (또는 alias 'ax-first=./.ax-first/.bin')"
    ;;

  *) die "알 수 없는 모드: $MODE (standalone | submodule)" ;;
esac

say "다음 단계: ax-first init [--preset ax]"
